name: Run Jupyter Notebook

permissions:
  contents: write  # Allow write access to the repository's contents
  
on:
  schedule:
    - cron: "30 4 * * 1"  # Every Monday at 3:30 AM UTC (equivalent to Sunday 7:30 or 8:30 PM PST depending on Daylight Savings)
  workflow_dispatch:  # Allows manual runs if needed

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install nbformat nbconvert pandas xlsxwriter jupyter ipykernel requests-cache retry-requests openmeteo-requests

      - name: Run Jupyter Notebook
        run: python run_notebook.py

      - name: Commit output
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add output_notebook.ipynb
          git commit -m "Update output notebook"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
